### ISSUE TITLE
99-dns这脚本好像执行不成功

### ISSUE THREAD

**Issue by zcracker** [kuretru/CloudXNS-DDNS#1]
99-dns这脚本好像执行不成功，重启路由器后ip不能更新，手动执行cloudxns-ddns.sh没问题

**Comment by kuretru** [comment]
第二行`[ "$INTERFACE" = wan1 ] || exit 0`，这里的接口你设置对了嘛，这里应该设置的是wan的名称，而不是pppoe-wan1，如果你没做过修改的话，OpenWrt默认应该是叫wan0，也就是可以通过ifup/ifdown命令可以启动/停止wan接口的网卡名称。
