### ISSUE TITLE
Small improvement

### ISSUE THREAD

**Issue by simonsmh** [kuretru/CloudXNS-DDNS#2]
value=$(curl members.3322.org/dyndns/getip)
岂不美哉
在内网的路由器都可以用
也用不着ifconfig了，在debian系下输出不同有bug

https://github.com/simonsmh/CloudXNS-DDNS/blob/master/CloudXNS-ddns.sh

**Comment by kuretru** [comment]
留给用户自由选择网卡的原因，是针对多WAN用户：可以将每一条WAN出口的IP更新到不同的主机头上，而不会造成错乱。  
如果需要自动填充IP，还是建议将interface留空，由CloudXNS自动获取你的IP，保证可用性(3322.org挂掉的情况下)。  
另外感谢反馈，该地址已收藏。
